import html from "eslint-plugin-html";

export default [
  {
    files: ["**/*.html"],
    plugins: { html },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        console: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Response: "readonly",
        Request: "readonly",
        Headers: "readonly",
        Blob: "readonly",
        FormData: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        crypto: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Date: "readonly",
        Array: "readonly",
        Object: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        RangeError: "readonly",
        SyntaxError: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        encodeURI: "readonly",
        encodeURIComponent: "readonly",
        decodeURI: "readonly",
        decodeURIComponent: "readonly",
        atob: "readonly",
        btoa: "readonly",
        queueMicrotask: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        HTMLElement: "readonly",
        SVGElement: "readonly",
        DOMParser: "readonly",
        Image: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        location: "readonly",
        performance: "readonly",
        event: "readonly",
        // CDN globals (Chart.js, html2canvas, jspdf)
        Chart: "readonly",
        html2canvas: "readonly",
        jspdf: "readonly",
        // App globals (defined in earlier inline script blocks or template contexts)
        payload: "readonly",
        base: "readonly",
        buildConflictMap: "readonly",
        fetchWithCORS: "readonly",
        fetchStooqMulti: "readonly",
      },
    },
    rules: {
      // Errors
      "no-undef": "error",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
      "no-constant-condition": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "no-self-compare": "error",
      "no-loss-of-precision": "error",
      "no-promise-executor-return": "warn",

      // Best practices
      "eqeqeq": ["warn", "always"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-throw-literal": "warn",
      "prefer-const": "warn",
      "no-var": "warn",
      "no-console": "off", // dashboard usa console para debug
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-fallthrough": "warn",

      // Style (relaxed — não impõe estilo severo)
      "semi": "off",
      "quotes": "off",
      "indent": "off",
      "comma-dangle": "off",
    },
  },
  {
    // Ignorar node_modules e ficheiros de backup
    ignores: ["node_modules/**", "**/*.bak", "__pycache__/**"],
  },
];
